services:
  backend-service:
    image: yash4200/insurance-backend:${BACKEND_TAG}
    container_name: insurance-backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: yash4200/insurance-frontend:${FRONTEND_TAG}
    container_name: insurance-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend-service
    restart: always
